server:
  port: 8112
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hhsyy/config-repo-test
          search-paths: test
          username: hhsyy
          password: hhs19951020
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


